# Generated by Django 4.1.1 on 2024-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
