# Generated by Django 4.1.1 on 2024-01-21 12:04

import brainshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainshare', '0003_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=brainshare.models.get_upload_path),
        ),
    ]
