# Generated by Django 4.1.1 on 2023-12-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_mediafile_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='story',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.ImageField(upload_to='status'),
        ),
    ]
